spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: mahboob
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  application:
    name: user-management
server:
  port: 8081
eureka:
  client:
    register-with-eureka: true
    eureka:
      client:
        serviceUrl:
          defaultZone=http://localhost:8761/eureka: